### PR TITLE
merge GetBlobsBundleV1 with GetPayloadV3 per spec update

### PR DESCRIPTION
**Pull request by roberto-bayardo**
ref: https://github.com/ethereum/execution-apis/pull/402

### CODE REVIEW

**Review by Inphi — APPROVED** [review]
looks good. We should also remove the get blobs bundle API from capabilities

**Review by Inphi — CHANGES_REQUESTED** [review]
oh i just realized. The execution payload codegen needs to be updated

**Comment by roberto-bayardo** [comment]
> looks good. We should also remove the get blobs bundle API from capabilities

done!

> oh i just realized. The execution payload codegen needs to be updated

right, I knew I was forgetting something. done!

**Review by Inphi — APPROVED** [review]
Looks good.
small nit: we can now get both the blobs bundle and payload from the cache as a single operation. This avoids a small chance of inconsistency if the raw payload was evicted immediately after we retrieved the block but before we attempted to read the blobs bundle.

**Comment by roberto-bayardo** [comment]
> Looks good. small nit: we can now get both the blobs bundle and payload from the cache as a single operation. This avoids a small chance of inconsistency if the raw payload was evicted immediately after we retrieved the block but before we attempted to read the blobs bundle.

right, let me fix that in the next PR where I'll also implement the proofs inclusion.

**Pull request merged**
