### PR TITLE
Merge with master

### PR DESCRIPTION
**Pull request by roberto-bayardo**
pulling in the latest upstream changes

### CODE REVIEW

**Comment by Inphi** [comment]
There are more commits in here than expected. Didn't we already merge https://github.com/mdehoog/go-ethereum/pull/43 to the eip-4844 branch?

**Comment by roberto-bayardo** [comment]
> There are more commits in here than expected. Didn't we already merge #43 to the eip-4844 branch?

yeah we did, wonder what I did wrong here. I started with eip-4844 branch, merged master into it, then have been doing a few more git merges against both eip-4844 and master in order to keep it up to date.  Git is still a bit of a mystery to me!

**Comment by Inphi** [comment]
Oh I see what happened. The earlier merge-with-master [merge PR](https://github.com/mdehoog/go-ethereum/pull/43) was squashed into a single [commit](https://github.com/mdehoog/go-ethereum/commit/c702b48542848b7a7cf26f7c97be053be1aae53c). Since we lost all individual commits, git couldn't tell if a merge had already taken place.

For this PR let's retain the commits as a "Merge pull request" so the diff on future merges is minimal.

**Review by Inphi — APPROVED** [review]
Thanks for being patient :-)

**Comment by roberto-bayardo** [comment]
> Oh I see what happened. The earlier merge-with-master [merge PR](https://github.com/mdehoog/go-ethereum/pull/43) was squashed into a single [commit](https://github.com/mdehoog/go-ethereum/commit/c702b48542848b7a7cf26f7c97be053be1aae53c). Since we lost all individual commits, git couldn't tell if a merge had already taken place.
> 
> For this PR let's retain the commits as a "Merge pull request" so the diff on future merges is minimal.

Ahah makes sense so one should never squash merge PRs. That would have made the next merge task a lot simpler too huh?

**Pull request merged**
